package com.glodblock.github.modularbees.common;

import com.glodblock.github.modularbees.common.blocks.centrifuge.BlockCentrifugeExport;
import com.glodblock.github.modularbees.common.blocks.centrifuge.BlockCentrifugeGearbox;
import com.glodblock.github.modularbees.common.blocks.centrifuge.BlockCentrifugeHeater;
import com.glodblock.github.modularbees.common.blocks.centrifuge.BlockCentrifugeImport;
import com.glodblock.github.modularbees.common.blocks.centrifuge.BlockCentrifugeOverclocker;
import com.glodblock.github.modularbees.common.blocks.centrifuge.BlockCentrifugePart;
import com.glodblock.github.modularbees.common.blocks.centrifuge.BlockModularCentrifuge;
import com.glodblock.github.modularbees.common.blocks.hive.BlockBeehiveAlveary;
import com.glodblock.github.modularbees.common.blocks.hive.BlockBeehiveDragon;
import com.glodblock.github.modularbees.common.blocks.hive.BlockBeehiveExport;
import com.glodblock.github.modularbees.common.blocks.hive.BlockBeehiveFeeder;
import com.glodblock.github.modularbees.common.blocks.hive.BlockBeehiveOverclocker;
import com.glodblock.github.modularbees.common.blocks.hive.BlockBeehivePart;
import com.glodblock.github.modularbees.common.blocks.hive.BlockBeehiveStacker;
import com.glodblock.github.modularbees.common.blocks.hive.BlockBeehiveTreater;
import com.glodblock.github.modularbees.common.blocks.hive.BlockModularBeehive;
import com.glodblock.github.modularbees.common.blocks.misc.BlockBeeExtractor;
import com.glodblock.github.modularbees.common.blocks.misc.BlockFluidDragonBreath;
import com.glodblock.github.modularbees.common.blocks.misc.BlockScentedPlank;
import com.glodblock.github.modularbees.common.fluids.FluidDragonBreath;
import com.glodblock.github.modularbees.common.items.ItemElectrode;
import com.glodblock.github.modularbees.common.items.ItemMB;
import com.glodblock.github.modularbees.common.tileentities.centrifuge.TileCentrifugeExport;
import com.glodblock.github.modularbees.common.tileentities.centrifuge.TileCentrifugeGearbox;
import com.glodblock.github.modularbees.common.tileentities.centrifuge.TileCentrifugeHeater;
import com.glodblock.github.modularbees.common.tileentities.centrifuge.TileCentrifugeImport;
import com.glodblock.github.modularbees.common.tileentities.centrifuge.TileCentrifugeOverclocker;
import com.glodblock.github.modularbees.common.tileentities.centrifuge.TileCentrifugePart;
import com.glodblock.github.modularbees.common.tileentities.centrifuge.TileModularCentrifuge;
import com.glodblock.github.modularbees.common.tileentities.hive.TileBeehiveAlveary;
import com.glodblock.github.modularbees.common.tileentities.hive.TileBeehiveDragon;
import com.glodblock.github.modularbees.common.tileentities.hive.TileBeehiveExport;
import com.glodblock.github.modularbees.common.tileentities.hive.TileBeehiveFeeder;
import com.glodblock.github.modularbees.common.tileentities.hive.TileBeehiveOverclocker;
import com.glodblock.github.modularbees.common.tileentities.hive.TileBeehivePart;
import com.glodblock.github.modularbees.common.tileentities.hive.TileBeehiveStacker;
import com.glodblock.github.modularbees.common.tileentities.hive.TileBeehiveTreater;
import com.glodblock.github.modularbees.common.tileentities.hive.TileModularBeehive;
import com.glodblock.github.modularbees.common.tileentities.misc.TileBeeExtractor;
import com.glodblock.github.modularbees.util.GameConstants;
import net.minecraft.world.item.BucketItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.Ingredient;
import net.neoforged.neoforge.common.Tags;

public class MBSingletons {

    public static BlockModularBeehive MODULAR_BEEHIVE_CORE;
    public static BlockBeehivePart MODULAR_BEEHIVE_PART;
    public static BlockBeehiveAlveary MODULAR_ALVEARY;
    public static BlockBeehiveFeeder MODULAR_FEEDER;
    public static BlockBeehiveOverclocker MODULAR_BEEHIVE_OVERCLOCKER;
    public static BlockBeehiveTreater MODULAR_TREATER;
    public static BlockBeehiveExport MODULAR_BEEHIVE_EXPORT;
    public static BlockBeehiveDragon MODULAR_DRAGON_HIVE;
    public static BlockBeehiveStacker MODULAR_BEEHIVE_STACKER;
    public static BlockScentedPlank SCENTED_PLANK;
    public static BlockFluidDragonBreath DRAGON_BREATH;
    public static BlockModularCentrifuge MODULAR_CENTRIFUGE_CORE;
    public static BlockCentrifugePart MODULAR_CENTRIFUGE_PART;
    public static BlockCentrifugeOverclocker MODULAR_CENTRIFUGE_OVERCLOCKER;
    public static BlockCentrifugeExport MODULAR_CENTRIFUGE_EXPORT;
    public static BlockCentrifugeImport MODULAR_CENTRIFUGE_IMPORT;
    public static BlockCentrifugeHeater MODULAR_CENTRIFUGE_HEATER;
    public static BlockCentrifugeGearbox MODULAR_CENTRIFUGE_GEARBOX;
    public static BlockBeeExtractor BEE_EXTRACTOR;

    public static ItemElectrode ELECTRODE_COPPER;
    public static ItemElectrode ELECTRODE_IRON;
    public static ItemElectrode ELECTRODE_GOLD;
    public static ItemElectrode ELECTRODE_NETHERITE;
    public static Item DRAGON_BREATH_BUCKET;
    public static ItemMB HONEY_JELLY;
    public static ItemMB LOYAL_TREAT;
    public static ItemMB ENDER_TREAT;
    public static ItemMB SOUL_TREAT;

    public static void init(MBRegistryHandler regHandler) {
        MODULAR_BEEHIVE_CORE = new BlockModularBeehive();
        MODULAR_BEEHIVE_PART = new BlockBeehivePart();
        MODULAR_ALVEARY = new BlockBeehiveAlveary();
        MODULAR_FEEDER = new BlockBeehiveFeeder();
        MODULAR_BEEHIVE_OVERCLOCKER = new BlockBeehiveOverclocker();
        MODULAR_TREATER = new BlockBeehiveTreater();
        MODULAR_BEEHIVE_EXPORT = new BlockBeehiveExport();
        MODULAR_DRAGON_HIVE = new BlockBeehiveDragon();
        MODULAR_BEEHIVE_STACKER = new BlockBeehiveStacker();
        MODULAR_CENTRIFUGE_CORE = new BlockModularCentrifuge();
        MODULAR_CENTRIFUGE_PART = new BlockCentrifugePart();
        MODULAR_CENTRIFUGE_OVERCLOCKER = new BlockCentrifugeOverclocker();
        MODULAR_CENTRIFUGE_EXPORT = new BlockCentrifugeExport();
        MODULAR_CENTRIFUGE_IMPORT = new BlockCentrifugeImport();
        MODULAR_CENTRIFUGE_HEATER = new BlockCentrifugeHeater();
        MODULAR_CENTRIFUGE_GEARBOX = new BlockCentrifugeGearbox();
        BEE_EXTRACTOR = new BlockBeeExtractor();
        SCENTED_PLANK = new BlockScentedPlank();
        DRAGON_BREATH = new BlockFluidDragonBreath();
        ELECTRODE_COPPER = new ItemElectrode(5 * GameConstants.MINUTE, Ingredient.of(Tags.Items.INGOTS_COPPER));
        ELECTRODE_IRON = new ItemElectrode(15 * GameConstants.MINUTE, Ingredient.of(Tags.Items.INGOTS_IRON));
        ELECTRODE_GOLD = new ItemElectrode(12 * GameConstants.MINUTE, Ingredient.of(Tags.Items.INGOTS_GOLD));
        ELECTRODE_NETHERITE = new ItemElectrode(25 * GameConstants.MINUTE, Ingredient.of(Tags.Items.INGOTS_NETHERITE));
        DRAGON_BREATH_BUCKET = new BucketItem(FluidDragonBreath.getFluid(), new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1));
        HONEY_JELLY = new ItemMB();
        LOYAL_TREAT = new ItemMB();
        ENDER_TREAT = new ItemMB();
        SOUL_TREAT = new ItemMB();
        regHandler.block("modular_beehive_core", MODULAR_BEEHIVE_CORE, TileModularBeehive.class, TileModularBeehive::new);
        regHandler.block("modular_beehive_part", MODULAR_BEEHIVE_PART, TileBeehivePart.class, TileBeehivePart::new);
        regHandler.block("modular_beehive_alveary", MODULAR_ALVEARY, TileBeehiveAlveary.class, TileBeehiveAlveary::new);
        regHandler.block("modular_beehive_feeder", MODULAR_FEEDER, TileBeehiveFeeder.class, TileBeehiveFeeder::new);
        regHandler.block("modular_beehive_overclocker", MODULAR_BEEHIVE_OVERCLOCKER, TileBeehiveOverclocker.class, TileBeehiveOverclocker::new);
        regHandler.block("modular_treater", MODULAR_TREATER, TileBeehiveTreater.class, TileBeehiveTreater::new);
        regHandler.block("modular_export", MODULAR_BEEHIVE_EXPORT, TileBeehiveExport.class, TileBeehiveExport::new);
        regHandler.block("modular_dragon_hive", MODULAR_DRAGON_HIVE, TileBeehiveDragon.class, TileBeehiveDragon::new);
        regHandler.block("modular_beehive_stacker", MODULAR_BEEHIVE_STACKER, TileBeehiveStacker.class, TileBeehiveStacker::new);
        regHandler.block("modular_centrifuge_core", MODULAR_CENTRIFUGE_CORE, TileModularCentrifuge.class, TileModularCentrifuge::new);
        regHandler.block("modular_centrifuge_part", MODULAR_CENTRIFUGE_PART, TileCentrifugePart.class, TileCentrifugePart::new);
        regHandler.block("modular_centrifuge_overclocker", MODULAR_CENTRIFUGE_OVERCLOCKER, TileCentrifugeOverclocker.class, TileCentrifugeOverclocker::new);
        regHandler.block("modular_centrifuge_export", MODULAR_CENTRIFUGE_EXPORT, TileCentrifugeExport.class, TileCentrifugeExport::new);
        regHandler.block("modular_centrifuge_import", MODULAR_CENTRIFUGE_IMPORT, TileCentrifugeImport.class, TileCentrifugeImport::new);
        regHandler.block("modular_centrifuge_heater", MODULAR_CENTRIFUGE_HEATER, TileCentrifugeHeater.class, TileCentrifugeHeater::new);
        regHandler.block("modular_centrifuge_gearbox", MODULAR_CENTRIFUGE_GEARBOX, TileCentrifugeGearbox.class, TileCentrifugeGearbox::new);
        regHandler.block("bee_extractor", BEE_EXTRACTOR, TileBeeExtractor.class, TileBeeExtractor::new);
        regHandler.block("scented_plank", SCENTED_PLANK);
        regHandler.item("electrode_copper", ELECTRODE_COPPER);
        regHandler.item("electrode_iron", ELECTRODE_IRON);
        regHandler.item("electrode_gold", ELECTRODE_GOLD);
        regHandler.item("electrode_netherite", ELECTRODE_NETHERITE);
        regHandler.item("dragon_breath_bucket", DRAGON_BREATH_BUCKET);
        regHandler.item("honey_jelly", HONEY_JELLY);
        regHandler.item("royal_treat", LOYAL_TREAT);
        regHandler.item("ender_treat", ENDER_TREAT);
        regHandler.item("soul_treat", SOUL_TREAT);
    }

}
