package com.glodblock.github.modularbees.common;

import com.glodblock.github.modularbees.common.blocks.centrifuge.BlockCentrifugeExport;
import com.glodblock.github.modularbees.common.blocks.centrifuge.BlockCentrifugeGearbox;
import com.glodblock.github.modularbees.common.blocks.centrifuge.BlockCentrifugeHeater;
import com.glodblock.github.modularbees.common.blocks.centrifuge.BlockCentrifugeImport;
import com.glodblock.github.modularbees.common.blocks.centrifuge.BlockCentrifugeOverclocker;
import com.glodblock.github.modularbees.common.blocks.centrifuge.BlockCentrifugePart;
import com.glodblock.github.modularbees.common.blocks.centrifuge.BlockModularCentrifuge;
import com.glodblock.github.modularbees.common.blocks.hive.BlockBeehiveAlveary;
import com.glodblock.github.modularbees.common.blocks.hive.BlockBeehiveDragon;
import com.glodblock.github.modularbees.common.blocks.hive.BlockBeehiveExport;
import com.glodblock.github.modularbees.common.blocks.hive.BlockBeehiveFeeder;
import com.glodblock.github.modularbees.common.blocks.hive.BlockBeehiveOverclocker;
import com.glodblock.github.modularbees.common.blocks.hive.BlockBeehivePart;
import com.glodblock.github.modularbees.common.blocks.hive.BlockBeehiveStacker;
import com.glodblock.github.modularbees.common.blocks.hive.BlockBeehiveTreater;
import com.glodblock.github.modularbees.common.blocks.hive.BlockModularBeehive;
import com.glodblock.github.modularbees.common.blocks.misc.BlockBeeExtractor;
import com.glodblock.github.modularbees.common.blocks.misc.BlockFluidDragonBreath;
import com.glodblock.github.modularbees.common.blocks.misc.BlockScentedPlank;
import com.glodblock.github.modularbees.common.fluids.FluidDragonBreath;
import com.glodblock.github.modularbees.common.items.ItemElectrode;
import com.glodblock.github.modularbees.common.items.ItemMB;
import com.glodblock.github.modularbees.common.tileentities.centrifuge.TileCentrifugeExport;
import com.glodblock.github.modularbees.common.tileentities.centrifuge.TileCentrifugeGearbox;
import com.glodblock.github.modularbees.common.tileentities.centrifuge.TileCentrifugeHeater;
import com.glodblock.github.modularbees.common.tileentities.centrifuge.TileCentrifugeImport;
import com.glodblock.github.modularbees.common.tileentities.centrifuge.TileCentrifugeOverclocker;
import com.glodblock.github.modularbees.common.tileentities.centrifuge.TileCentrifugePart;
import com.glodblock.github.modularbees.common.tileentities.centrifuge.TileModularCentrifuge;
import com.glodblock.github.modularbees.common.tileentities.hive.TileBeehiveAlveary;
import com.glodblock.github.modularbees.common.tileentities.hive.TileBeehiveDragon;
import com.glodblock.github.modularbees.common.tileentities.hive.TileBeehiveExport;
import com.glodblock.github.modularbees.common.tileentities.hive.TileBeehiveFeeder;
import com.glodblock.github.modularbees.common.tileentities.hive.TileBeehiveOverclocker;
import com.glodblock.github.modularbees.common.tileentities.hive.TileBeehivePart;
import com.glodblock.github.modularbees.common.tileentities.hive.TileBeehiveStacker;
import com.glodblock.github.modularbees.common.tileentities.hive.TileBeehiveTreater;
import com.glodblock.github.modularbees.common.tileentities.hive.TileModularBeehive;
import com.glodblock.github.modularbees.common.tileentities.misc.TileBeeExtractor;
import com.glodblock.github.modularbees.util.GameConstants;
import net.minecraft.world.item.BucketItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.neoforged.neoforge.common.Tags;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredItem;
import org.jetbrains.annotations.NotNull;

public class MBSingletons {

    public static DeferredBlock<@NotNull BlockModularBeehive> MODULAR_BEEHIVE_CORE;
    public static DeferredBlock<@NotNull BlockBeehivePart> MODULAR_BEEHIVE_PART;
    public static DeferredBlock<@NotNull BlockBeehiveAlveary> MODULAR_ALVEARY;
    public static DeferredBlock<@NotNull BlockBeehiveFeeder> MODULAR_FEEDER;
    public static DeferredBlock<@NotNull BlockBeehiveOverclocker> MODULAR_BEEHIVE_OVERCLOCKER;
    public static DeferredBlock<@NotNull BlockBeehiveTreater> MODULAR_TREATER;
    public static DeferredBlock<@NotNull BlockBeehiveExport> MODULAR_BEEHIVE_EXPORT;
    public static DeferredBlock<@NotNull BlockBeehiveDragon> MODULAR_DRAGON_HIVE;
    public static DeferredBlock<@NotNull BlockBeehiveStacker> MODULAR_BEEHIVE_STACKER;
    public static DeferredBlock<@NotNull BlockScentedPlank> SCENTED_PLANK;
    public static DeferredBlock<@NotNull BlockFluidDragonBreath> DRAGON_BREATH;
    public static DeferredBlock<@NotNull BlockModularCentrifuge> MODULAR_CENTRIFUGE_CORE;
    public static DeferredBlock<@NotNull BlockCentrifugePart> MODULAR_CENTRIFUGE_PART;
    public static DeferredBlock<@NotNull BlockCentrifugeOverclocker> MODULAR_CENTRIFUGE_OVERCLOCKER;
    public static DeferredBlock<@NotNull BlockCentrifugeExport> MODULAR_CENTRIFUGE_EXPORT;
    public static DeferredBlock<@NotNull BlockCentrifugeImport> MODULAR_CENTRIFUGE_IMPORT;
    public static DeferredBlock<@NotNull BlockCentrifugeHeater> MODULAR_CENTRIFUGE_HEATER;
    public static DeferredBlock<@NotNull BlockCentrifugeGearbox> MODULAR_CENTRIFUGE_GEARBOX;
    public static DeferredBlock<@NotNull BlockBeeExtractor> BEE_EXTRACTOR;

    public static DeferredItem<@NotNull ItemElectrode> ELECTRODE_COPPER;
    public static DeferredItem<@NotNull ItemElectrode> ELECTRODE_IRON;
    public static DeferredItem<@NotNull ItemElectrode> ELECTRODE_GOLD;
    public static DeferredItem<@NotNull ItemElectrode> ELECTRODE_NETHERITE;
    public static DeferredItem<@NotNull Item> DRAGON_BREATH_BUCKET;
    public static DeferredItem<@NotNull ItemMB> HONEY_JELLY;
    public static DeferredItem<@NotNull ItemMB> LOYAL_TREAT;
    public static DeferredItem<@NotNull ItemMB> ENDER_TREAT;
    public static DeferredItem<@NotNull ItemMB> SOUL_TREAT;

    public static void init(MBRegistryHandler regHandler) {
        MODULAR_BEEHIVE_CORE = regHandler.block("modular_beehive_core", BlockModularBeehive::new, TileModularBeehive.class, TileModularBeehive::new);
        MODULAR_BEEHIVE_PART = regHandler.block("modular_beehive_part", BlockBeehivePart::new, TileBeehivePart.class, TileBeehivePart::new);
        MODULAR_ALVEARY = regHandler.block("modular_beehive_alveary", BlockBeehiveAlveary::new, TileBeehiveAlveary.class, TileBeehiveAlveary::new);
        MODULAR_FEEDER = regHandler.block("modular_beehive_feeder", BlockBeehiveFeeder::new, TileBeehiveFeeder.class, TileBeehiveFeeder::new);
        MODULAR_BEEHIVE_OVERCLOCKER = regHandler.block("modular_beehive_overclocker", BlockBeehiveOverclocker::new, TileBeehiveOverclocker.class, TileBeehiveOverclocker::new);
        MODULAR_TREATER = regHandler.block("modular_treater", BlockBeehiveTreater::new, TileBeehiveTreater.class, TileBeehiveTreater::new);
        MODULAR_BEEHIVE_EXPORT = regHandler.block("modular_export", BlockBeehiveExport::new, TileBeehiveExport.class, TileBeehiveExport::new);
        MODULAR_DRAGON_HIVE = regHandler.block("modular_dragon_hive", BlockBeehiveDragon::new, TileBeehiveDragon.class, TileBeehiveDragon::new);
        MODULAR_BEEHIVE_STACKER = regHandler.block("modular_beehive_stacker", BlockBeehiveStacker::new, TileBeehiveStacker.class, TileBeehiveStacker::new);
        MODULAR_CENTRIFUGE_CORE = regHandler.block("modular_centrifuge_core", BlockModularCentrifuge::new, TileModularCentrifuge.class, TileModularCentrifuge::new);
        MODULAR_CENTRIFUGE_PART = regHandler.block("modular_centrifuge_part", BlockCentrifugePart::new, TileCentrifugePart.class, TileCentrifugePart::new);
        MODULAR_CENTRIFUGE_OVERCLOCKER = regHandler.block("modular_centrifuge_overclocker", BlockCentrifugeOverclocker::new, TileCentrifugeOverclocker.class, TileCentrifugeOverclocker::new);
        MODULAR_CENTRIFUGE_EXPORT = regHandler.block("modular_centrifuge_export", BlockCentrifugeExport::new, TileCentrifugeExport.class, TileCentrifugeExport::new);
        MODULAR_CENTRIFUGE_IMPORT = regHandler.block("modular_centrifuge_import", BlockCentrifugeImport::new, TileCentrifugeImport.class, TileCentrifugeImport::new);
        MODULAR_CENTRIFUGE_HEATER = regHandler.block("modular_centrifuge_heater", BlockCentrifugeHeater::new, TileCentrifugeHeater.class, TileCentrifugeHeater::new);
        MODULAR_CENTRIFUGE_GEARBOX = regHandler.block("modular_centrifuge_gearbox", BlockCentrifugeGearbox::new, TileCentrifugeGearbox.class, TileCentrifugeGearbox::new);
        BEE_EXTRACTOR = regHandler.block("bee_extractor", BlockBeeExtractor::new, TileBeeExtractor.class, TileBeeExtractor::new);
        SCENTED_PLANK = regHandler.block("scented_plank", BlockScentedPlank::new);
        DRAGON_BREATH = regHandler.fluidBlock("dragon_breath", BlockFluidDragonBreath::new);
        ELECTRODE_COPPER = regHandler.item("electrode_copper", p -> new ItemElectrode(p, 5 * GameConstants.MINUTE, Tags.Items.INGOTS_COPPER));
        ELECTRODE_IRON = regHandler.item("electrode_iron", p -> new ItemElectrode(p, 15 * GameConstants.MINUTE, Tags.Items.INGOTS_IRON));
        ELECTRODE_GOLD = regHandler.item("electrode_gold", p -> new ItemElectrode(p, 12 * GameConstants.MINUTE, Tags.Items.INGOTS_GOLD));
        ELECTRODE_NETHERITE = regHandler.item("electrode_netherite", p -> new ItemElectrode(p, 25 * GameConstants.MINUTE, Tags.Items.INGOTS_NETHERITE));
        DRAGON_BREATH_BUCKET = regHandler.item("dragon_breath_bucket", p -> new BucketItem(FluidDragonBreath.getFluid(), p.craftRemainder(Items.BUCKET).stacksTo(1)));
        HONEY_JELLY = regHandler.item("honey_jelly", ItemMB::new);
        LOYAL_TREAT = regHandler.item("royal_treat", ItemMB::new);
        ENDER_TREAT = regHandler.item("ender_treat", ItemMB::new);
        SOUL_TREAT = regHandler.item("soul_treat", ItemMB::new);
    }

}
